export const PRODUCT_LOAD_IN_PROGRESS = 'PRODUCT_LOAD_IN_PROGRESS';
export const PRODUCT_LOAD_FAIL = 'PRODUCT_LOAD_FAIL';
// export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';